version: '3.8'

services:
  app1:
    build: .
    container_name: app1
    restart: always
    environment:
      - PORT=3001

  app2:
    build: .
    container_name: app2
    restart: always
    environment:
      - PORT=3002
  
  app3:
    build: .
    container_name: app3
    restart: always
    environment:
      - PORT=3003

  app4:
    build: .
    container_name: app4
    restart: always
    environment:
      - PORT=3004

  # in real world you will use the native NGINX instead of this container one.
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8002:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
      - app3
      - app4
